In [46]:
# Cleaned Submission

import pandas as pd
import numpy as np

# Change later so others can get it on their computer (debaaaaaaaaaaaaajo)

employees = pd.read_csv("C:/Users/Michael Botelho/bip-python-unh/user_audit/data/employees.csv")
system_access = pd.read_csv("C:/Users/Michael Botelho/bip-python-unh/user_audit/data/system_access.csv")


##### Cleaning ID's that works
system_access = system_access.astype(str)
str(system_access['id'])
system_access['id'] = system_access['id'].apply('EMP''{:0>6}'.format)
str(employees['employee_number'])

##### Merge Datasets

df = pd.merge(employees, system_access, left_on='employee_number', right_on='id',  how='outer')


##### Filter for missing values

df.isnull().any()

##### Subset of records that are missing
 
nd = df[df.isnull().any(axis=1)]


##### Set Access Level according to Title


conditions = [
    (df['title'] == 'Sales Assistant'),
    (df['title'] == 'Account Manager'),
(df['title'] == 'Director of Sales')]

values = ['Contract Entry', 'Account Admin', 'Approval - Manager']
df['access_level'] = np.select(conditions, values)
del df['id']


#pd.set_option('display.min_rows', 25)
df

,employee_number,first_name,last_name,email,title,access_level
0,EMP003037,Juliana,Burbudge,juliana.burbudge@consultants.com,Director of Sales,Approval - Manager
1,EMP003045,Lizzie,Blue,lizzie.blue@consultants.com,Sales Assistant,Contract Entry
2,EMP003051,Marjory,Selcraig,marjory.selcraig@consultants.com,Sales Assistant,Contract Entry
3,EMP003068,Aguste,O'Connor,aguste.o'connor@consultants.com,Sales Assistant,Contract Entry
4,EMP003097,Clemens,Kopman,clemens.kopman@consultants.com,Account Manager,Account Admin
5,EMP003133,Donielle,Midgley,donielle.midgley@consultants.com,Sales Assistant,Contract Entry
6,EMP003134,Marcela,Thieme,marcela.thieme@consultants.com,Sales Assistant,Contract Entry
7,EMP003180,Haily,Wadeson,haily.wadeson@consultants.com,Sales Assistant,Contract Entry
8,EMP003265,Natala,Judd,natala.judd@consultants.com,Director of Sales,Approval - Manager
9,EMP003287,Gayla,Aldin,gayla.aldin@consultants.com,Sales Assistant,Contract Entry
10,EMP003291,Gweneth,Abbate,gweneth.abbate@consultants.com,Account Manager,Account Admin
11,EMP003299,Nerte,Luipold,nerte.luipold@consultants.com,Account Manager,Account Admin
...,...,...,...,...,...,...
963,EMP024677,Anastasia,Caudell,anastasia.caudell@consultants.com,Account Manager,Account Admin
964,EMP024686,Yorke,Tremathick,yorke.tremathick@consultants.com,Account Manager,Account Admin
965,EMP024699,Dosi,Brunetti,dosi.brunetti@consultants.com,Sales Assistant,Contract Entry
966,EMP024739,Winny,Santarelli,winny.santarelli@consultants.com,Sales Assistant,Contract Entry
967,EMP024740,Ebenezer,Worsnap,ebenezer.worsnap@consultants.com,Director of Sales,Approval - Manager
968,EMP024823,Toni,Wrates,toni.wrates@consultants.com,Sales Assistant,Contract Entry
969,EMP024862,Ronna,Meltetal,ronna.meltetal@consultants.com,Sales Assistant,Contract Entry
970,EMP024864,Kristina,Yakov,kristina.yakov@consultants.com,Sales Assistant,Contract Entry
971,EMP024885,Margarita,Habbergham,margarita.habbergham@consultants.com,Account Manager,Account Admin
972,EMP024890,Prescott,Southward,prescott.southward@consultants.com,Sales Assistant,Contract Entry
973,EMP024896,Raine,Learned,raine.learned@consultants.com,Account Manager,Account Admin
974,EMP024931,Frederique,Fant,frederique.fant@consultants.com,Account Manager,Account Admin

In [32]:
# NOTAS & Uncleaned Work


import pandas as pd
import numpy as np

# Change later so others can get it on their computer (debaaaaaaaaaaaaajo)

employees = pd.read_csv("C:/Users/Michael Botelho/bip-python-unh/user_audit/data/employees.csv")
system_access = pd.read_csv("C:/Users/Michael Botelho/bip-python-unh/user_audit/data/system_access.csv")



#########################################################################################################################
##### Trying to clean the ID's in System Access

#system_access['id'] = ['EMP'.zfill(6)]
#system_access['id'] = system_access['id'].apply('EMP'.zfill(6))
#system_access['id'] = system_access['id'].apply('EMP'.zfill(6))
#print(system_access)
#print(employees)

##### Cleaning ID's that works
system_access = system_access.astype(str)
str(system_access['id'])
system_access['id'] = system_access['id'].apply('EMP''{:0>6}'.format)
str(employees['employee_number'])

##### Merge Datasets
#df = pd.merge(employees, system_access, left_on='employee_number', right_on='id', inplace=True)
df = pd.merge(employees, system_access, left_on='employee_number', right_on='id',  how='outer')
df

##### Filter for missing values

df.isnull().any()

df

##### Subset of records that are missing
 
nd = df[df.isnull().any(axis=1)]


##### if title = x then access level = z : .iloc .loc ?????

#null_data.loc[null_data.title == 'Sales Assistant', null_data.access_level] = 'Contract Entry'
#df.loc[['viper', 'sidewinder'], ['shield']] = 50
#null_data.loc[null_data.title == 'Sales Assistant', null_data.access_level] = 'Contract Entry'
#df.loc[df['set_of_numbers'] <= 4, 'equal_or_lower_than_4?'] = 'True' 
#null_data.loc[null_data['title'] == 'Sales Assistant', null_data['access_level']] = 'Contract Entry'
#nd.loc[nd['title'].isnull(),'Sales Assistant'] = nd['access_level']
#nd.loc['Sales Assistant'], nd['access_level'] = 'Contract Entry'
#nd['access_level1'] = np.where(nd.title== 'Sales Assistant', 'Contract Entry')
#nd.loc[nd['title'] == 'Sales Assistant'] = 'Contract Entry'
#conditions = [
#    (nd['title'] == 'Sales Assistant'),
 #   (nd['title'] == 'Account Manager'),
#(nd['title'] == 'Director of Sales')]
#values = ['Contract Entry', 'Account Admin', 'Approval - Manager']
#pd.options.mode.chained_assignment = None  # default='warn'
#del nd['access_level']
#nd['access_level'] = np.select(conditions, values)
#nd

##### This works


conditions = [
    (df['title'] == 'Sales Assistant'),
    (df['title'] == 'Account Manager'),
(df['title'] == 'Director of Sales')]

values = ['Contract Entry', 'Account Admin', 'Approval - Manager']
df['access_level'] = np.select(conditions, values)
del df['id']
#pd.set_option('display.max_rows', None)
# wooooooooooooooooooooooooooooooooooooooooooooooooooooooo

In [ ]:
# Do this stuff later (for the importing)

import pandas as pd

def load_data():
    df_contracts = pd.read_csv('../data/contracts.csv')
    df_customers = pd.read_csv('../data/customers.csv')
    return df_contracts, df_customers

def combine_data(df_contracts, df_customers):
    df_customers.rename(columns={'id':'customer_id'}, inplace=True)
    df_customers.set_index('customer_id', inplace=True)
    df_contracts.set_index('customer_id', inplace=True)
    df = df_contracts.join(df_customers, how='left')
    return df

In [ ]:
import sys
sys.path.insert(1, '../src')
import ians_work